/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MySideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface MyStockPrice {
        "stockSymbol": string;
    }
    interface MyTooltip {
        "text": string;
    }
}
declare global {
    interface HTMLMySideDrawerElement extends Components.MySideDrawer, HTMLStencilElement {
    }
    var HTMLMySideDrawerElement: {
        prototype: HTMLMySideDrawerElement;
        new (): HTMLMySideDrawerElement;
    };
    interface HTMLMyStockPriceElement extends Components.MyStockPrice, HTMLStencilElement {
    }
    var HTMLMyStockPriceElement: {
        prototype: HTMLMyStockPriceElement;
        new (): HTMLMyStockPriceElement;
    };
    interface HTMLMyTooltipElement extends Components.MyTooltip, HTMLStencilElement {
    }
    var HTMLMyTooltipElement: {
        prototype: HTMLMyTooltipElement;
        new (): HTMLMyTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "my-side-drawer": HTMLMySideDrawerElement;
        "my-stock-price": HTMLMyStockPriceElement;
        "my-tooltip": HTMLMyTooltipElement;
    }
}
declare namespace LocalJSX {
    interface MySideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface MyStockPrice {
        "stockSymbol"?: string;
    }
    interface MyTooltip {
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-side-drawer": MySideDrawer;
        "my-stock-price": MyStockPrice;
        "my-tooltip": MyTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-side-drawer": LocalJSX.MySideDrawer & JSXBase.HTMLAttributes<HTMLMySideDrawerElement>;
            "my-stock-price": LocalJSX.MyStockPrice & JSXBase.HTMLAttributes<HTMLMyStockPriceElement>;
            "my-tooltip": LocalJSX.MyTooltip & JSXBase.HTMLAttributes<HTMLMyTooltipElement>;
        }
    }
}
